#!/usr/bin/env node
/**
 * Generates QuestDP sitemap files from the same SEO route manifest used by the
 * static HTML generator. Quiz URLs are intentionally excluded until each
 * question page has a separate quality and rights review.
 */
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { SITE_ORIGIN, getSeoRouteManifest } from './seo-route-manifest.mjs';

const __filename = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');
const PUBLIC_DIR = path.join(REPO_ROOT, 'public');

const manifest = getSeoRouteManifest();

const groups = [
  {
    file: 'sitemap-core.xml',
    label: 'core',
    routes: manifest.core.filter((route) => route.path !== '/blog'),
  },
  {
    file: 'sitemap-blog.xml',
    label: 'blog',
    routes: [
      ...manifest.core.filter((route) => route.path === '/blog'),
      ...manifest.blog,
    ],
  },
  {
    file: 'sitemap-lessons.xml',
    label: 'lessons',
    routes: manifest.lessons,
  },
];

for (const group of groups) {
  writeXml(group.file, buildUrlset(group.routes, group.label));
}
writeXml('sitemap.xml', buildSitemapIndex(groups));

const total = groups.reduce((sum, group) => sum + group.routes.length, 0);
console.log(
  `sitemap generated: total ${total} URLs ` +
    `(core ${groups[0].routes.length}, blog ${groups[1].routes.length}, lessons ${groups[2].routes.length}, quiz 0)`,
);

function writeXml(fileName, xml) {
  fs.writeFileSync(path.join(PUBLIC_DIR, fileName), xml, 'utf8');
}

function buildSitemapIndex(items) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...items.map((item) =>
      [
        '  <sitemap>',
        `    <loc>${SITE_ORIGIN}/${item.file}</loc>`,
        '  </sitemap>',
      ].join('\n'),
    ),
    '</sitemapindex>',
    '',
  ].join('\n');
}

function buildUrlset(routes, label) {
  const quiz = routes.find((route) => route.path.startsWith('/quiz/'));
  if (quiz) {
    throw new Error(`Quiz route leaked into ${label} sitemap: ${quiz.path}`);
  }
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<!-- QuestDP ${label} sitemap. Generated by scripts/generate-sitemap.mjs. -->`,
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...routes.map((route) =>
      [
        '  <url>',
        `    <loc>${route.canonical}</loc>`,
        `    <changefreq>${route.changefreq}</changefreq>`,
        `    <priority>${route.priority}</priority>`,
        '  </url>',
      ].join('\n'),
    ),
    '</urlset>',
    '',
  ].join('\n');
}
