#!/usr/bin/env node
/**
 * Generates QuestDP sitemap files from the same SEO route manifest used by the
 * static HTML generator. Quiz URLs are intentionally excluded until each
 * question page has a separate quality and rights review.
 */
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { SITE_ORIGIN, getSeoRouteManifest } from './seo-route-manifest.mjs';

const __filename = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');
const PUBLIC_DIR = path.join(REPO_ROOT, 'public');

const manifest = getSeoRouteManifest();

const groups = [
  {
    file: 'sitemap-core.xml',
    label: 'core',
    routes: manifest.core.filter((route) => route.path !== '/blog'),
  },
  {
    file: 'sitemap-blog.xml',
    label: 'blog',
    routes: [
      ...manifest.core.filter((route) => route.path === '/blog'),
      ...manifest.blog,
    ],
  },
  {
    file: 'sitemap-lessons.xml',
    label: 'lessons',
    routes: manifest.lessons.filter(isIndexableRoute),
  },
  {
    file: 'sitemap-topics.xml',
    label: 'topics',
    routes: manifest.topics,
  },
];

for (const group of groups) {
  writeXml(group.file, buildUrlset(group.routes, group.label));
}
writeXml('sitemap.xml', buildSitemapIndex(groups));
writeXml('rss.xml', buildRssFeed(manifest.blog));

const total = groups.reduce((sum, group) => sum + group.routes.length, 0);
console.log(
  `sitemap generated: total ${total} URLs ` +
    `(core ${groups[0].routes.length}, blog ${groups[1].routes.length}, lessons ${groups[2].routes.length}, topics ${groups[3].routes.length}, quiz 0)`,
);

function writeXml(fileName, xml) {
  fs.writeFileSync(path.join(PUBLIC_DIR, fileName), xml, 'utf8');
}

function buildSitemapIndex(items) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...items.map((item) =>
      [
        '  <sitemap>',
        `    <loc>${SITE_ORIGIN}/${item.file}</loc>`,
        '  </sitemap>',
      ].join('\n'),
    ),
    '</sitemapindex>',
    '',
  ].join('\n');
}

function buildUrlset(routes, label) {
  const quiz = routes.find((route) => route.path.startsWith('/quiz/'));
  if (quiz) {
    throw new Error(`Quiz route leaked into ${label} sitemap: ${quiz.path}`);
  }
  const hasImages = routes.some((route) => route.images?.length);
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<!-- QuestDP ${label} sitemap. Generated by scripts/generate-sitemap.mjs. -->`,
    hasImages
      ? '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">'
      : '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...routes.map((route) =>
      [
        '  <url>',
        `    <loc>${route.canonical}</loc>`,
        `    <changefreq>${route.changefreq}</changefreq>`,
        `    <priority>${route.priority}</priority>`,
        ...renderImages(route.images),
        '  </url>',
      ].join('\n'),
    ),
    '</urlset>',
    '',
  ].join('\n');
}

function buildRssFeed(blogRoutes) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss version="2.0">',
    '  <channel>',
    '    <title>QuestDP 공부법 블로그</title>',
    `    <link>${SITE_ORIGIN}/blog/</link>`,
    '    <description>ADsP, SQLD, 컴활 자격증을 처음 공부하는 사람을 위한 QuestDP 공부법 글 모음입니다.</description>',
    '    <language>ko-KR</language>',
    ...blogRoutes.map((route) =>
      [
        '    <item>',
        `      <title>${xmlEscape(route.h1)}</title>`,
        `      <link>${route.canonical}</link>`,
        `      <guid isPermaLink="true">${route.canonical}</guid>`,
        `      <description>${xmlEscape(route.description || route.summary)}</description>`,
        '    </item>',
      ].join('\n'),
    ),
    '  </channel>',
    '</rss>',
    '',
  ].join('\n');
}

function renderImages(images = []) {
  return images.map((image) =>
    [
      '    <image:image>',
      `      <image:loc>${xmlEscape(image.url)}</image:loc>`,
      image.title ? `      <image:title>${xmlEscape(image.title)}</image:title>` : '',
      image.caption ? `      <image:caption>${xmlEscape(image.caption)}</image:caption>` : '',
      '    </image:image>',
    ].filter(Boolean).join('\n'),
  );
}

function isIndexableRoute(route) {
  return route.indexable !== false;
}

function xmlEscape(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
