-- 0050 — Seed SQLD modeling stage and ANSI/SPARC micro-step questions.
--
-- The SQLD 1-1 lesson now splits two long steps into beginner-friendly
-- micro steps:
--   1) 모델링 단계: 개념적 / 논리적 / 물리적
--   2) ANSI/SPARC: 외부 / 개념 / 내부 / 데이터 독립성
--
-- Keep the server question bank aligned with the local LessonStep.quizId
-- values so v2 lesson play can reserve these questions by id.

insert into public.questions (
  id, subject, chapter, chapter_title, topic, canonical_topic, subtopic,
  pass_number, difficulty, stem, choices, answer_index, explanation,
  lifecycle, is_playable, source_path, updated_at
) values
  (
    'sqld-1-1-cp-02',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '데이터 모델링 단계의 순서로 옳은 것은?',
    '["물리적 → 논리적 → 개념적","개념적 → 물리적 → 논리적","개념적 → 논리적 → 물리적","논리적 → 개념적 → 물리적"]'::jsonb,
    2,
    '"데이터 모델링 단계는 개념적 → 논리적 → 물리적 순서입니다. 큰 그림을 잡고, 구조를 정리하고, 마지막에 실제 DBMS에 맞게 구현합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-02-conceptual',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '개념적 모델링에 가장 가까운 설명은?',
    '["Oracle에 맞춰 컬럼 자료형과 인덱스를 정한다","업무의 핵심 대상과 관계를 큰 그림으로 잡는다","정규화를 적용해 키와 관계를 정밀하게 다듬는다","서버 저장 공간을 어떻게 배치할지 정한다"]'::jsonb,
    1,
    '"개념적 모델링은 업무의 큰 그림을 잡는 단계입니다. 어떤 대상이 있고 어떻게 연결되는지 먼저 봅니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-02-logical',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '논리적 모델링에 가장 가까운 설명은?',
    '["사용자별 화면만 따로 만든다","DB 서버의 디스크 저장 위치를 정한다","키, 관계, 중복 제거 등 DB 구조를 정밀하게 정리한다","업무의 큰 대상만 대략적으로 나열한다"]'::jsonb,
    2,
    '"논리적 모델링은 개념적 모델을 더 정밀한 DB 구조로 정리하는 단계입니다. 키, 관계, 정규화, 재사용성 같은 표현과 연결됩니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-02-physical',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '물리적 모델링에 가장 가까운 설명은?',
    '["실제 DBMS에 맞춰 자료형, 인덱스, 저장 방식을 정한다","업무의 핵심 대상과 관계만 큰 그림으로 잡는다","조직 전체 통합 스키마를 사용자별로 나눈다","응용 프로그램별 화면 이름만 정한다"]'::jsonb,
    0,
    '"물리적 모델링은 실제 DBMS에 맞춰 구현하는 단계입니다. 자료형, 인덱스, 저장 공간, 성능 같은 표현과 연결됩니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-03',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    'ANSI/SPARC 3-스키마가 나누는 3층으로 알맞은 묶음은?',
    '["외부 스키마 · 내부 스키마 · 응용 스키마","사용자 스키마 · 관리자 스키마 · 저장 스키마","외부 스키마 · 개념 스키마 · 내부 스키마","개념적 모델링 · 논리적 모델링 · 물리적 모델링"]'::jsonb,
    2,
    '"ANSI/SPARC 3-스키마는 외부 스키마, 개념 스키마, 내부 스키마로 나뉩니다. 이 단계에서는 먼저 \"외개내\"라는 3층 이름을 잡으면 됩니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-03-external',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '외부 스키마에 가장 가까운 설명은?',
    '["DB가 디스크에 실제로 저장되는 방식","조직 전체 DB 구조의 통합 표현","사용자나 응용 프로그램별로 보이는 화면 또는 뷰","DBMS 내부의 인덱스와 파일 배치"]'::jsonb,
    2,
    '"외부 스키마는 사용자나 응용 프로그램별로 보이는 DB의 모습입니다. 사용자별 뷰, 여러 개 존재 같은 표현과 연결됩니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-03-conceptual',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '학교 전체 DB의 ''중앙 설계도''를 고른다면 무엇일까?\n\n학생 화면, 교수 화면처럼 따로 보이는 화면이 아니라 모든 사용자 정보를 하나로 모아 정리한 전체 구조야.',
    '["사용자별 화면만 여러 개로 나눈 구조","조직 전체 DB 구조를 통합해서 표현한 구조","인덱스와 파일 저장 위치를 정한 구조","특정 응용 프로그램만을 위한 임시 화면"]'::jsonb,
    1,
    '"개념 스키마는 DB 전체 구조를 하나로 정리한 중앙 설계도입니다. 사용자별 화면은 외부 스키마, 실제 저장 방식은 내부 스키마입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-03-internal',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '내부 스키마에 가장 가까운 설명은?',
    '["사용자별로 보이는 화면 구조","조직 전체의 논리적 통합 구조","데이터가 실제 저장장치에 저장되는 방식","업무의 큰 그림을 그리는 단계"]'::jsonb,
    2,
    '"내부 스키마는 실제 저장 구조와 관련됩니다. 물리 저장, 저장장치, 파일 구조, 인덱스 같은 표현과 연결됩니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-03-independence',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '물리적 독립성에 가장 가까운 상황은?',
    '["새 테이블을 추가했더니 사용자 화면이 모두 바뀐다","인덱스나 저장 위치를 바꿔도 개념·외부 스키마 영향이 적다","사용자별 화면을 여러 개 만드는 것이다","조직 전체 DB 구조를 하나로 통합한다"]'::jsonb,
    1,
    '"물리적 독립성은 내부 스키마가 바뀌어도 개념 스키마와 외부 스키마에 주는 영향을 줄이는 성질입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  )
on conflict (id) do update set
  subject = excluded.subject,
  chapter = excluded.chapter,
  chapter_title = excluded.chapter_title,
  topic = excluded.topic,
  canonical_topic = excluded.canonical_topic,
  subtopic = excluded.subtopic,
  pass_number = excluded.pass_number,
  difficulty = excluded.difficulty,
  stem = excluded.stem,
  choices = excluded.choices,
  answer_index = excluded.answer_index,
  explanation = excluded.explanation,
  lifecycle = excluded.lifecycle,
  is_playable = excluded.is_playable,
  source_path = excluded.source_path,
  updated_at = now();
