-- 0051 — Seed SQLD entity and performance micro-step questions.
--
-- SQLD 1-1/1-2 now split dense textbook-style concepts into mobile-first
-- micro steps. Keep the server question bank aligned with local quizId values.

insert into public.questions (
  id, subject, chapter, chapter_title, topic, canonical_topic, subtopic,
  pass_number, difficulty, stem, choices, answer_index, explanation,
  lifecycle, is_playable, source_path, updated_at
) values
  (
    'sqld-1-1-cp-04',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '엔터티(Entity)에 가장 가까운 설명은?',
    '["DB에서 관리하고 싶은 대상","SQL 실행 순서","화면 디자인 색상","서버 배포 방식"]'::jsonb,
    0,
    '"엔터티는 업무에서 관리해야 하는 대상입니다. DB에서는 보통 테이블 후보가 됩니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-04-requirements',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '엔터티의 요건으로 옳지 않은 것은?',
    '["업무에서 필요해야 한다","유일하게 식별 가능해야 한다","반드시 영구 저장되어야 한다","다른 엔터티와 관계가 있을 수 있어야 한다"]'::jsonb,
    2,
    '"엔터티는 영속 저장이 필수 요건은 아닙니다. 임시로 관리하는 대상도 엔터티가 될 수 있습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-04-naming',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '엔터티 이름 짓기 규칙으로 가장 적절한 것은?',
    '["약어를 많이 사용한다","현업에서 쓰는 단수 명사를 사용한다","같은 이름을 여러 곳에서 반복한다","의미가 모호해도 짧으면 좋다"]'::jsonb,
    1,
    '"엔터티 이름은 현업 용어를 쓰고, 약어를 지양하며, 단수 명사로 명확하게 짓는 것이 좋습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-05-kind',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '“수강신청”처럼 특정 시점에 발생한 일을 나타내는 엔터티 분류는?',
    '["유형 엔터티","개념 엔터티","사건 엔터티","기본 엔터티"]'::jsonb,
    2,
    '"수강신청, 주문, 결제처럼 특정 시점에 발생한 일은 사건 엔터티로 볼 수 있습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-05-time',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '발생 시점에 따른 엔터티 분류에 해당하는 것은?',
    '["기본 엔터티","개념 엔터티","유형 엔터티","복합 엔터티"]'::jsonb,
    0,
    '"발생 시점 분류는 기본·중심·행위 엔터티입니다. 유형·개념·사건은 유무형 분류입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-05-check',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '다음 중 서로 다른 분류 기준이 섞인 보기는?',
    '["유형·개념·사건","기본·중심·행위","학생·과목·수강신청","기본·중심·관계"]'::jsonb,
    3,
    '"기본·중심·행위가 발생 시점 분류입니다. 관계 엔터티는 이 분류명이 아닙니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-06',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '속성(Attribute)에 가장 가까운 설명은?',
    '["엔터티의 세부 정보","테이블 간 연결선","데이터베이스 서버 이름","SQL 명령어 묶음"]'::jsonb,
    0,
    '"속성은 엔터티를 설명하는 세부 정보입니다. 테이블에서는 보통 컬럼이 됩니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-06-origin',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '다른 속성에서 계산해 만든 “총점”은 어떤 속성인가?',
    '["기본 속성","설계 속성","파생 속성","외래 속성"]'::jsonb,
    2,
    '"파생 속성은 다른 속성에서 계산하거나 가공해서 만든 속성입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-06-shape',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '한 학생이 여러 개의 이메일을 가질 수 있다면 이메일은 어떤 분류에 가까운가?',
    '["단일 속성","복합 속성","다중값 속성","주식별자"]'::jsonb,
    2,
    '"한 인스턴스가 여러 값을 가질 수 있으면 다중값 속성입니다. 보통 별도 테이블로 분리합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-06-role',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '다른 테이블의 기본키를 참조하는 속성은?',
    '["PK 속성","FK 속성","파생 속성","복합 속성"]'::jsonb,
    1,
    '"FK 속성은 다른 엔터티의 식별자를 참조하는 속성입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-07',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '관계(Relationship)에 가장 가까운 설명은?',
    '["엔터티 사이의 업무적 연결","속성의 값 범위","테이블의 저장 위치","화면의 색상 규칙"]'::jsonb,
    0,
    '"관계는 엔터티들이 업무적으로 어떻게 연결되는지 표현합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-07-elements',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '관계의 3요소 “관차선”에 포함되지 않는 것은?',
    '["관계명","차수","선택사양","파생속성"]'::jsonb,
    3,
    '"관차선은 관계명, 차수, 선택사양입니다. 파생속성은 속성 분류와 관련된 용어입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-07-cardinality',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '부서 하나에 여러 사원이 소속될 때 가장 자연스러운 차수는?',
    '["1:1","1:M","M:N","0:0"]'::jsonb,
    1,
    '"부서 하나가 여러 사원과 연결되므로 1:M 관계입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-07-bridge',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '학생과 과목의 M:N 관계를 관계형 DB로 풀 때 중간에 두기 좋은 엔터티는?',
    '["수강신청","학과명","학생이름","과목설명"]'::jsonb,
    0,
    '"M:N 관계는 수강신청 같은 교차 엔터티를 넣어 두 개의 1:M 관계로 풀 수 있습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-08',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '식별자의 역할로 가장 적절한 것은?',
    '["인스턴스를 구분한다","SQL 문장을 정렬한다","화면 색상을 지정한다","서버 비용을 계산한다"]'::jsonb,
    0,
    '"식별자는 엔터티 안의 각 인스턴스를 구분하는 값입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-08-types',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '식별자 분류 기준으로 옳지 않은 것은?',
    '["주식별자/보조식별자","내부식별자/외부식별자","단일식별자/복합식별자","삽입식별자/삭제식별자"]'::jsonb,
    3,
    '"식별자 분류에는 주/보조, 내부/외부, 단일/복합, 본질/인조 등이 있습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-08-main',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '주식별자 4요건 “유최불존”에 해당하지 않는 것은?',
    '["유일성","최소성","불변성","의미성"]'::jsonb,
    3,
    '"주식별자 4요건은 유일성·최소성·불변성·존재성입니다. 의미성은 요건이 아닙니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-09',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '식별자 관계의 핵심 특징은?',
    '["부모 식별자가 자식 PK에 포함된다","부모 식별자가 화면 색상에 쓰인다","자식이 부모를 전혀 참조하지 않는다","항상 M:N으로만 표현된다"]'::jsonb,
    0,
    '"식별자 관계는 부모의 식별자가 자식의 주식별자 일부가 되는 관계입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-09-nonident',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '비식별자 관계에 가장 가까운 설명은?',
    '["부모 식별자가 자식의 일반 속성/FK로만 존재한다","부모 식별자가 자식 PK에 반드시 포함된다","자식 테이블이 존재할 수 없다","무조건 1:1 관계다"]'::jsonb,
    0,
    '"비식별자 관계에서는 부모 식별자가 자식의 PK가 아니라 일반 속성 또는 FK로 존재합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-09-compare',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '식별자 관계와 비식별자 관계를 가르는 가장 중요한 기준은?',
    '["부모 식별자가 자식 PK에 포함되는지","테이블 이름이 한글인지","속성이 3개 이상인지","데이터가 영구 저장되는지"]'::jsonb,
    0,
    '"부모 식별자가 자식 PK에 포함되면 식별자 관계, 포함되지 않으면 비식별자 관계로 봅니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-10',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '후보키 중 대표로 선택되어 테이블의 행을 구분하는 키는?',
    '["기본키","외래키","슈퍼키","대체키"]'::jsonb,
    0,
    '"기본키는 후보키 중 대표로 선택한 키입니다. 테이블의 각 행을 구분하는 중심 키입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-10-integrity',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '외래키가 실제 존재하는 부모 값을 참조해야 한다는 규칙은?',
    '["개체 무결성","참조 무결성","도메인 무결성","정렬 무결성"]'::jsonb,
    1,
    '"참조 무결성은 FK가 존재하지 않는 부모를 가리키지 않도록 보장하는 규칙입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-10-pk-unique',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    'PK와 UNIQUE의 차이로 가장 적절한 것은?',
    '["PK는 대표 식별자이고 NULL을 허용하지 않는다","UNIQUE는 항상 테이블당 하나만 가능하다","PK는 중복을 허용한다","UNIQUE는 외래키만 만들 수 있다"]'::jsonb,
    0,
    '"PK는 테이블 대표 식별자이며 NULL을 허용하지 않습니다. UNIQUE는 중복 방지 제약입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-01',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '이상 현상(Anomaly) 3종에 해당하지 않는 것은?',
    '["삽입 이상","삭제 이상","갱신 이상","조회 이상"]'::jsonb,
    3,
    '"이상 현상은 삽입·삭제·갱신 이상입니다. 조회 이상은 표준 분류가 아닙니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-01-insert',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '신설 학과만 등록하고 싶은데 학생 정보까지 필요하다면 어떤 이상인가?',
    '["삽입 이상","삭제 이상","갱신 이상","정렬 이상"]'::jsonb,
    0,
    '"원하는 정보만 넣지 못하고 불필요한 정보가 필요하면 삽입 이상입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-01-delete',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '마지막 학생을 삭제했더니 학과 정보까지 사라지는 문제는?',
    '["삽입 이상","삭제 이상","갱신 이상","도메인 이상"]'::jsonb,
    1,
    '"삭제하면서 보존해야 할 정보까지 사라지면 삭제 이상입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-01-update',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '같은 학과명이 여러 행에 있어 일부만 수정되어 모순이 생기는 문제는?',
    '["삽입 이상","삭제 이상","갱신 이상","참조 이상"]'::jsonb,
    2,
    '"일부만 갱신되어 같은 정보가 서로 달라지면 갱신 이상입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-02',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    'A 값을 알면 B 값이 하나로 결정될 때 쓰는 표현은?',
    '["A → B","A ⊕ B","A LIKE B","A ORDER B"]'::jsonb,
    0,
    '"A가 B를 결정하면 A → B로 표현합니다. 이때 A는 결정자, B는 종속자입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-02-full',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '복합키 전체가 있어야 성적이 결정되는 경우는?',
    '["완전 함수 종속","부분 함수 종속","이행 함수 종속","참조 종속"]'::jsonb,
    0,
    '"기본키 전체에 종속되면 완전 함수 종속입니다. 복합키 일부만으로는 결정되지 않아야 합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-02-partial',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '복합키 중 일부만으로 학생이름이 결정되는 경우는?',
    '["완전 함수 종속","부분 함수 종속","이행 함수 종속","도메인 종속"]'::jsonb,
    1,
    '"복합키 일부에만 종속되면 부분 함수 종속입니다. 이를 제거하면 제2정규형으로 갑니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-02-transitive',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '학번 → 학과코드 → 학과명처럼 간접으로 결정되는 관계는?',
    '["완전 함수 종속","부분 함수 종속","이행 함수 종속","외래 함수 종속"]'::jsonb,
    2,
    '"한 번 건너서 결정되는 구조는 이행 함수 종속입니다. 학번 → 학과코드 → 학과명이 대표 예입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-03',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '정규형 순서로 옳은 것은?',
    '["1NF → 2NF → 3NF → BCNF","BCNF → 3NF → 2NF → 1NF","2NF → 1NF → BCNF → 3NF","1NF → BCNF → 2NF → 3NF"]'::jsonb,
    0,
    '"정규형은 1NF, 2NF, 3NF, BCNF 순서로 조건이 강해집니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-03-1nf',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '1NF가 요구하는 핵심 조건은?',
    '["속성 값의 원자성","부분 종속 제거","이행 종속 제거","모든 결정자가 후보키"]'::jsonb,
    0,
    '"1NF는 한 칸에 하나의 값, 즉 원자값을 요구합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-03-2nf',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '2NF에서 제거해야 하는 것은?',
    '["부분 함수 종속","이행 함수 종속","모든 후보키","참조 무결성"]'::jsonb,
    0,
    '"2NF는 부분 함수 종속을 제거한 상태입니다. 복합키 일부에만 매달린 속성을 분리합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-03-3nf',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '3NF에서 제거해야 하는 것은?',
    '["부분 함수 종속","이행 함수 종속","모든 기본키","정렬 기준"]'::jsonb,
    1,
    '"3NF는 이행 함수 종속을 제거한 상태입니다. 기본키가 아닌 속성끼리의 간접 종속을 줄입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-03-bcnf',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    'BCNF의 핵심 조건은?',
    '["모든 결정자가 후보키다","모든 속성이 NULL이다","모든 테이블을 하나로 합친다","모든 FK를 삭제한다"]'::jsonb,
    0,
    '"BCNF는 모든 결정자가 후보키인 더 강한 정규형입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-04',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '반정규화를 고려하기 가장 적절한 상황은?',
    '["조회 시 반복 JOIN으로 응답이 느릴 때","중복을 무조건 0으로 만들어야 할 때","PK를 삭제해야 할 때","데이터를 절대 조회하지 않을 때"]'::jsonb,
    0,
    '"반정규화는 주로 조회 성능 개선을 위해 고려합니다. 반복 JOIN이나 집계가 병목일 때 검토합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-04-methods',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '반정규화 방법에 해당하는 것은?',
    '["요약 테이블 생성","모든 컬럼 삭제","PK 중복 허용","WHERE 절 금지"]'::jsonb,
    0,
    '"요약 테이블, 컬럼 중복, 파생 컬럼, 테이블 통합 등이 반정규화 방법입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-04-tradeoff',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '반정규화의 대가로 가장 적절한 것은?',
    '["갱신 부담과 일관성 리스크 증가","모든 JOIN 제거로 무조건 안전","저장 공간이 항상 감소","무결성 문제가 자동 해결"]'::jsonb,
    0,
    '"중복을 허용하므로 갱신 부담과 일관성 리스크가 커질 수 있습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-05',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '특수 관계의 예로 가장 적절한 것은?',
    '["사원 테이블의 상사사번이 다시 사원 테이블을 참조한다","모든 테이블을 삭제한다","컬럼명을 영어로만 쓴다","NULL을 0으로 바꾼다"]'::jsonb,
    0,
    '"같은 엔터티를 다시 참조하는 구조는 계층형/순환 관계의 예입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-05-hierarchy',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '계층형 관계를 다루는 대표 방식으로 적절한 것은?',
    '["셀프 조인","테이블 삭제","PK 제거","무조건 반정규화"]'::jsonb,
    0,
    '"사원-상사처럼 같은 테이블을 참조하는 구조는 셀프 조인 등으로 다룰 수 있습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-05-exclusive',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '상호배타 관계에 가장 가까운 예시는?',
    '["결제는 카드 또는 계좌이체 중 하나만 선택된다","학생은 이름을 반드시 가진다","학번은 중복될 수 없다","점수는 평균을 낸다"]'::jsonb,
    0,
    '"상호배타 관계는 여러 부모 후보 중 하나만 선택되는 구조입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-06',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '트랜잭션에 가장 가까운 설명은?',
    '["하나로 묶어 처리해야 하는 DB 작업 단위","화면의 카드 색상","컬럼 이름 규칙","검색엔진 설명문"]'::jsonb,
    0,
    '"트랜잭션은 여러 SQL을 하나의 논리 작업 단위로 묶는 개념입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-06-acid',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    'ACID 중 “전부 성공 또는 전부 취소”를 뜻하는 것은?',
    '["원자성","일관성","고립성","지속성"]'::jsonb,
    0,
    '"원자성은 트랜잭션이 전부 성공하거나 전부 취소되어야 한다는 성질입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-06-isolation',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '격리수준이 강해지는 순서로 옳은 것은?',
    '["Read Uncommitted → Read Committed → Repeatable Read → Serializable","Serializable → Repeatable Read → Read Committed → Read Uncommitted","Read Committed → Read Uncommitted → Serializable → Repeatable Read","Repeatable Read → Serializable → Read Uncommitted → Read Committed"]'::jsonb,
    0,
    '"일반적으로 RU < RC < RR < Serializable 순서로 강해집니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-07',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    'NULL에 대한 설명으로 옳은 것은?',
    '["0과 같은 값이다","값이 없거나 알 수 없다는 의미에 가깝다","항상 TRUE다","무조건 정렬에서 맨 앞이다"]'::jsonb,
    1,
    '"NULL은 0이나 빈 문자열이 아니라 값이 없거나 알 수 없음을 나타냅니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-07-compare',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    'NULL 값을 찾을 때 올바른 조건은?',
    '["col = NULL","col <> NULL","col IS NULL","col LIKE NULL"]'::jsonb,
    2,
    '"NULL 여부는 IS NULL 또는 IS NOT NULL로 확인해야 합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-07-aggregate',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    'COUNT(*)와 COUNT(컬럼)의 차이로 옳은 것은?',
    '["COUNT(*)는 NULL 행도 포함해 행 수를 센다","COUNT(컬럼)은 항상 COUNT(*)와 같다","COUNT(*)는 NULL이 있으면 실패한다","COUNT(컬럼)은 NULL만 센다"]'::jsonb,
    0,
    '"COUNT(*)는 행 수를 세므로 NULL이 있어도 포함합니다. COUNT(컬럼)은 NULL을 제외합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-07-sort',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    'Oracle 기준 ORDER BY ASC에서 NULL의 기본 위치로 가장 가까운 것은?',
    '["맨 뒤","맨 앞","항상 중간","정렬 불가"]'::jsonb,
    0,
    '"Oracle은 ASC 정렬에서 NULL을 큰 값처럼 다뤄 뒤쪽에 둡니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-08',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '본질식별자에 가까운 예시는?',
    '["학번","자동 증가 id","UUID","랜덤 시퀀스"]'::jsonb,
    0,
    '"본질식별자는 업무에 원래 존재하는 식별자입니다. 학번은 본질식별자에 가깝습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-08-surrogate',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '인조식별자를 쓰는 이유로 적절한 것은?',
    '["업무 정책 변화와 개인정보 노출 리스크를 줄일 수 있다","항상 사람이 의미를 바로 알 수 있다","중복 검증이 절대 필요 없다","모든 FK가 자동 삭제된다"]'::jsonb,
    0,
    '"인조식별자는 의미 없는 내부 ID라서 업무 값 변경과 개인정보 노출에 강합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-08-practice',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '실무에서 가장 안정적인 식별자 설계에 가까운 것은?',
    '["인조 PK + 본질 값 UNIQUE","주민번호를 모든 테이블 PK로 직접 사용","PK 없이 이름만 사용","중복을 허용하고 나중에 수동 정리"]'::jsonb,
    0,
    '"PK는 인조식별자로 안정적으로 두고, 업무상 중복되면 안 되는 값은 UNIQUE로 관리하는 방식이 흔합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  )
on conflict (id) do update set
  subject = excluded.subject,
  chapter = excluded.chapter,
  chapter_title = excluded.chapter_title,
  topic = excluded.topic,
  canonical_topic = excluded.canonical_topic,
  subtopic = excluded.subtopic,
  pass_number = excluded.pass_number,
  difficulty = excluded.difficulty,
  stem = excluded.stem,
  choices = excluded.choices,
  answer_index = excluded.answer_index,
  explanation = excluded.explanation,
  lifecycle = excluded.lifecycle,
  is_playable = excluded.is_playable,
  source_path = excluded.source_path,
  updated_at = now();
