-- 0060 - Seed SQLD attribute shape and role micro steps.
--
-- Attribute shape and role classifications are now split into beginner-friendly
-- single/composite/multivalue and PK/FK/general steps. These rows keep
-- server-side reservation and grading aligned with the local lesson JSON.

insert into public.questions (
  id, subject, chapter, chapter_title, topic, canonical_topic, subtopic,
  pass_number, difficulty, stem, choices, answer_index, explanation,
  lifecycle, is_playable, source_path, updated_at
) values
  (
    'sqld-1-1-cp-06-shape-single',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '다음 중 단일 속성에 가장 가까운 것은?',
    '["주소처럼 시/구/상세주소로 나눌 수 있는 값","학번처럼 하나의 의미로 쓰는 값","이메일처럼 여러 개 등록할 수 있는 값","총점처럼 계산해서 만든 값"]'::jsonb,
    1,
    '"단일 속성은 하나의 의미로 쓰는 속성입니다. 학번처럼 더 쪼개 관리할 필요가 없는 값을 떠올리면 쉽습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-06-shape-composite',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '다음 중 복합 속성으로 보기 가장 쉬운 것은?',
    '["학번","주소","학생ID","총점"]'::jsonb,
    1,
    '"주소는 시, 구, 상세주소처럼 하위 속성으로 나눠 볼 수 있으므로 복합 속성에 가깝습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-06-shape',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    2,
    '한 학생이 여러 개의 이메일을 가질 수 있다면 이메일은 어떤 분류에 가까운가?',
    '["단일 속성","복합 속성","다중값 속성","주식별자"]'::jsonb,
    2,
    '"한 인스턴스가 여러 값을 가질 수 있으면 다중값 속성입니다. 보통 별도 테이블로 분리합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-06-role-pk',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '학생 표에서 한 학생을 겹치지 않게 구분하는 대표 속성은?',
    '["학생 이름","학번","전화번호","학과명"]'::jsonb,
    1,
    '"학번은 학생 한 명을 유일하게 구분하는 대표값으로 쓸 수 있으므로 PK 속성에 가깝습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-06-role',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '학생 표의 학과ID가 학과 표의 학과ID를 가리킨다면, 학생 표의 학과ID는?',
    '["PK 속성","FK 속성","일반 속성","파생 속성"]'::jsonb,
    1,
    '"FK 속성은 다른 테이블의 대표값을 참조해 두 테이블을 연결하는 속성입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-1-cp-06-role-general',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    '데이터 모델링의 이해',
    null,
    1,
    1,
    '다음 중 일반 속성에 가장 가까운 것은?',
    '["학생을 대표로 구분하는 학번","학과 표를 가리키는 학과ID","학생을 설명하는 이름","다른 값으로 계산한 총점"]'::jsonb,
    2,
    '"이름은 PK처럼 행을 대표로 구분하거나 FK처럼 다른 테이블을 참조하는 값이 아니라, 학생을 설명하는 일반 속성입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  )
on conflict (id) do update set
  subject = excluded.subject,
  chapter = excluded.chapter,
  chapter_title = excluded.chapter_title,
  topic = excluded.topic,
  canonical_topic = excluded.canonical_topic,
  subtopic = excluded.subtopic,
  pass_number = excluded.pass_number,
  difficulty = excluded.difficulty,
  stem = excluded.stem,
  choices = excluded.choices,
  answer_index = excluded.answer_index,
  explanation = excluded.explanation,
  lifecycle = excluded.lifecycle,
  is_playable = excluded.is_playable,
  source_path = excluded.source_path,
  updated_at = now();
