-- 0063 - Update SQLD data model and performance Part 2 drills.
--
-- Part 2 now follows the beginner-first content-edit pattern used in the
-- refreshed SQLD modeling lessons: one small concept, one clear example, and
-- one immediate drill. These upserts keep server-side lesson reservations and
-- grading aligned with the local concept-practice JSON.

insert into public.questions (
  id, subject, chapter, chapter_title, topic, canonical_topic, subtopic,
  pass_number, difficulty, stem, choices, answer_index, explanation,
  lifecycle, is_playable, source_path, updated_at
) values
  (
    'sqld-1-2-cp-01',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '이상 현상(Anomaly) 3종에 해당하지 않는 것은?',
    '["삽입 이상","삭제 이상","갱신 이상","조회 이상"]'::jsonb,
    3,
    '"이상 현상은 삽입·삭제·갱신 이상입니다. 조회 이상은 표준 분류가 아닙니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-01-insert',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '신설 학과만 저장하고 싶은데 학생 정보까지 있어야 저장된다. 어떤 이상인가?',
    '["삽입 이상","삭제 이상","갱신 이상","정렬 이상"]'::jsonb,
    0,
    '"원하는 정보만 넣지 못하고 불필요한 정보까지 요구되면 삽입 이상입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-01-delete',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '마지막 학생 행을 지웠더니 학과 정보까지 사라졌다. 어떤 이상인가?',
    '["삽입 이상","삭제 이상","갱신 이상","도메인 이상"]'::jsonb,
    1,
    '"삭제하면서 보존해야 할 정보까지 사라지면 삭제 이상입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-01-update',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '같은 학과명이 여러 행에 있어 일부만 수정되며 서로 다른 이름이 남았다. 어떤 이상인가?',
    '["삽입 이상","삭제 이상","갱신 이상","참조 이상"]'::jsonb,
    2,
    '"중복된 값을 일부만 고쳐 데이터가 서로 모순되면 갱신 이상입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-02',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '학번을 알면 학생 이름이 하나로 정해진다. 이 관계를 가장 잘 표현한 것은?',
    '["이름 → 학번","학번 → 이름","학번 LIKE 이름","학번 ORDER 이름"]'::jsonb,
    1,
    '"학번이 이름을 결정하므로 학번 → 이름으로 표현합니다. 왼쪽은 결정자, 오른쪽은 종속자입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-02-full',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '학번과 과목코드를 함께 알아야 성적이 결정된다. 가장 가까운 설명은?',
    '["부분 함수 종속","이행 함수 종속","완전 함수 종속","참조 종속"]'::jsonb,
    2,
    '"복합키 전체가 있어야 값이 결정되면 완전 함수 종속입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-02-partial',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    'PK가 학번+과목코드인데 학생이름은 학번만으로 결정된다. 어떤 종속인가?',
    '["완전 함수 종속","이행 함수 종속","도메인 종속","부분 함수 종속"]'::jsonb,
    3,
    '"복합키 전체가 아니라 일부 키에만 매달린 속성이 있으면 부분 함수 종속입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-02-transitive',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '학번 → 학과코드 → 학과명처럼 한 번 거쳐서 결정되는 관계는?',
    '["완전 함수 종속","이행 함수 종속","부분 함수 종속","외래 함수 종속"]'::jsonb,
    1,
    '"A가 B를 정하고 B가 C를 정해 A가 C까지 간접으로 정하면 이행 함수 종속입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-03',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '정규형 순서로 옳은 것은?',
    '["1NF → 2NF → 3NF → BCNF","BCNF → 3NF → 2NF → 1NF","2NF → 1NF → BCNF → 3NF","1NF → BCNF → 2NF → 3NF"]'::jsonb,
    0,
    '"정규형은 1NF, 2NF, 3NF, BCNF 순서로 조건이 강해집니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-03-1nf',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '1NF가 요구하는 핵심 조건은?',
    '["부분 종속 제거","모든 결정자가 후보키","속성 값의 원자성","이행 종속 제거"]'::jsonb,
    2,
    '"1NF는 한 칸에 하나의 값, 즉 원자값을 요구합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-03-2nf',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '2NF에서 제거해야 하는 것은?',
    '["이행 함수 종속","부분 함수 종속","모든 후보키","참조 무결성"]'::jsonb,
    1,
    '"2NF는 복합키 일부에만 매달린 부분 함수 종속을 제거한 상태입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-03-3nf',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '3NF에서 제거해야 하는 것은?',
    '["부분 함수 종속","모든 기본키","정렬 기준","이행 함수 종속"]'::jsonb,
    3,
    '"3NF는 기본키가 아닌 속성끼리 이어지는 이행 함수 종속을 제거한 상태입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-03-bcnf',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    'BCNF의 핵심 조건은?',
    '["모든 결정자가 후보키다","모든 속성이 NULL이다","모든 테이블을 하나로 합친다","모든 FK를 삭제한다"]'::jsonb,
    0,
    '"BCNF는 모든 결정자가 후보키인 더 강한 정규형입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-04',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '반정규화를 고려하기 가장 적절한 상황은?',
    '["PK를 삭제해야 할 때","데이터를 절대 조회하지 않을 때","조회 시 반복 JOIN으로 응답이 느릴 때","중복을 무조건 0으로 만들어야 할 때"]'::jsonb,
    2,
    '"반정규화는 주로 조회 성능 개선을 위해 고려합니다. 반복 JOIN이나 집계가 병목일 때 검토합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-04-methods',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '반정규화 방법에 해당하는 것은?',
    '["모든 컬럼 삭제","PK 중복 허용","WHERE 절 금지","월별 매출 요약 테이블 생성"]'::jsonb,
    3,
    '"요약 테이블, 컬럼 중복, 파생 컬럼, 테이블 통합 등이 반정규화 방법입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-04-tradeoff',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '반정규화의 대가로 가장 적절한 것은?',
    '["모든 JOIN 제거로 무조건 안전","갱신 부담과 일관성 리스크 증가","저장 공간이 항상 감소","무결성 문제가 자동 해결"]'::jsonb,
    1,
    '"중복을 허용하므로 수정할 곳이 늘고, 일부만 바뀌면 값이 서로 달라질 수 있습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-05',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '특수 관계의 예로 가장 적절한 것은?',
    '["모든 테이블을 삭제한다","컬럼명을 영어로만 쓴다","사원 테이블의 상사사번이 다시 사원 테이블을 참조한다","NULL을 0으로 바꾼다"]'::jsonb,
    2,
    '"같은 엔터티를 다시 참조하는 구조는 계층형/순환 관계의 예입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-05-hierarchy',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '사원과 상사처럼 같은 테이블 안에서 위아래 구조를 다루는 대표 방식은?',
    '["셀프 조인","테이블 삭제","PK 제거","무조건 반정규화"]'::jsonb,
    0,
    '"사원-상사처럼 같은 테이블을 다시 참조하는 구조는 셀프 조인 등으로 다룰 수 있습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-05-exclusive',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '상호배타 관계에 가장 가까운 예시는?',
    '["학생은 이름을 반드시 가진다","학번은 중복될 수 없다","점수는 평균을 낸다","결제는 카드 또는 계좌이체 중 하나만 선택된다"]'::jsonb,
    3,
    '"상호배타 관계는 여러 후보 중 하나만 선택되는 구조입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-06',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '트랜잭션에 가장 가까운 설명은?',
    '["화면의 카드 색상","하나로 묶어 처리해야 하는 DB 작업 단위","컬럼 이름 규칙","검색엔진 설명문"]'::jsonb,
    1,
    '"트랜잭션은 여러 SQL을 하나의 논리 작업 단위로 묶는 개념입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-06-acid',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    'ACID 중 “전부 성공 또는 전부 취소”를 뜻하는 것은?',
    '["일관성","고립성","원자성","지속성"]'::jsonb,
    2,
    '"원자성은 트랜잭션이 전부 성공하거나 전부 취소되어야 한다는 성질입니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-06-isolation',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '격리수준이 강해지는 순서로 옳은 것은?',
    '["Read Uncommitted → Read Committed → Repeatable Read → Serializable","Serializable → Repeatable Read → Read Committed → Read Uncommitted","Read Committed → Read Uncommitted → Serializable → Repeatable Read","Repeatable Read → Serializable → Read Uncommitted → Read Committed"]'::jsonb,
    0,
    '"일반적으로 RU < RC < RR < Serializable 순서로 강해집니다. 강할수록 일관성은 좋아지지만 성능 부담이 커질 수 있습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-07',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    'NULL에 대한 설명으로 옳은 것은?',
    '["0과 같은 값이다","항상 TRUE다","무조건 정렬에서 맨 앞이다","값이 없거나 알 수 없다는 의미에 가깝다"]'::jsonb,
    3,
    '"NULL은 0이나 빈 문자열이 아니라 값이 없거나 알 수 없음을 나타냅니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-07-compare',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    'NULL 값을 찾을 때 올바른 조건은?',
    '["col = NULL","col <> NULL","col IS NULL","col LIKE NULL"]'::jsonb,
    2,
    '"NULL 여부는 IS NULL 또는 IS NOT NULL로 확인해야 합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-07-aggregate',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    'COUNT(*)와 COUNT(컬럼)의 차이로 옳은 것은?',
    '["COUNT(컬럼)은 항상 COUNT(*)와 같다","COUNT(*)는 NULL 행도 포함해 행 수를 센다","COUNT(*)는 NULL이 있으면 실패한다","COUNT(컬럼)은 NULL만 센다"]'::jsonb,
    1,
    '"COUNT(*)는 행 수를 세므로 NULL이 있어도 포함합니다. COUNT(컬럼)은 NULL을 제외합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-07-sort',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    'Oracle 기준 ORDER BY ASC에서 NULL의 기본 위치로 가장 가까운 것은?',
    '["맨 뒤","맨 앞","항상 중간","정렬 불가"]'::jsonb,
    0,
    '"Oracle은 ASC 정렬에서 NULL을 큰 값처럼 다뤄 뒤쪽에 둡니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-08',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    1,
    '본질식별자에 가까운 예시는?',
    '["자동 증가 id","UUID","학번","랜덤 시퀀스"]'::jsonb,
    2,
    '"본질식별자는 업무에 원래 존재하는 식별자입니다. 학번은 본질식별자에 가깝습니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-08-surrogate',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '인조식별자를 쓰는 이유로 적절한 것은?',
    '["항상 사람이 의미를 바로 알 수 있다","업무 정책 변화와 개인정보 노출 리스크를 줄일 수 있다","중복 검증이 절대 필요 없다","모든 FK가 자동 삭제된다"]'::jsonb,
    1,
    '"인조식별자는 의미 없는 내부 ID라서 업무 값 변경과 개인정보 노출에 강합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-1-2-cp-08-practice',
    'sqld',
    1,
    '데이터 모델링의 이해',
    '데이터 모델과 성능',
    '데이터 모델과 성능',
    null,
    1,
    2,
    '실무에서 가장 안정적인 식별자 설계에 가까운 것은?',
    '["주민번호를 모든 테이블 PK로 직접 사용","PK 없이 이름만 사용","중복을 허용하고 나중에 수동 정리","인조 PK + 본질 값 UNIQUE"]'::jsonb,
    3,
    '"PK는 인조식별자로 안정적으로 두고, 업무상 중복되면 안 되는 값은 UNIQUE로 관리하는 방식이 흔합니다."'::jsonb,
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  )
on conflict (id) do update set
  subject = excluded.subject,
  chapter = excluded.chapter,
  chapter_title = excluded.chapter_title,
  topic = excluded.topic,
  canonical_topic = excluded.canonical_topic,
  subtopic = excluded.subtopic,
  pass_number = excluded.pass_number,
  difficulty = excluded.difficulty,
  stem = excluded.stem,
  choices = excluded.choices,
  answer_index = excluded.answer_index,
  explanation = excluded.explanation,
  lifecycle = excluded.lifecycle,
  is_playable = excluded.is_playable,
  source_path = excluded.source_path,
  updated_at = now();
