-- 0068 - Seed SQLD subject 2 visual follow-up drills.
--
-- These IDs are connected from src/data/lessons/sqld/ch2-sql.ts via
-- extraQuizIds. Keeping them in public.questions prevents server-side lesson
-- reservation failures when users press "문제 풀기".

insert into public.questions (
  id,
  subject,
  chapter,
  chapter_title,
  topic,
  canonical_topic,
  subtopic,
  pass_number,
  difficulty,
  stem,
  choices,
  answer_index,
  explanation,
  lifecycle,
  is_playable,
  source_path,
  updated_at
) values
  (
    'sqld-2-1-cp-02-sql-map',
    'sqld',
    2,
    'SQL 기본 및 활용',
    'SQL 기본',
    'SQL 기본',
    '관계대수',
    1,
    1,
    '관계대수 기호와 SQL 절의 연결로 가장 적절한 것은?',
    '["σ는 조건에 맞는 행을 고르는 연산이므로 WHERE와 가깝다","π는 여러 테이블을 합치는 연산이므로 JOIN과 같다","×는 중복을 제거하는 연산이므로 DISTINCT와 같다","∩는 모든 가능한 행 조합을 만들므로 CROSS JOIN과 같다"]'::jsonb,
    0,
    to_jsonb('σ(Selection)는 조건을 만족하는 행을 고르는 연산이라 WHERE와 가깝습니다. π는 열 선택, ×는 카티시안 곱, ∩는 교집합입니다.'::text),
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-2-1-cp-10-where-flow',
    'sqld',
    2,
    'SQL 기본 및 활용',
    'SQL 기본',
    'SQL 기본',
    'WHERE 절',
    1,
    2,
    'WHERE 절에 대한 설명으로 옳은 것은?',
    '["WHERE는 GROUP BY 이후의 집계 결과를 필터링한다","WHERE에서는 SELECT에서 만든 별칭을 항상 사용할 수 있다","WHERE는 GROUP BY보다 먼저 실행되어 행 단위 조건을 걸러낸다","WHERE는 ORDER BY보다 뒤에 실행되어 정렬 결과만 필터링한다"]'::jsonb,
    2,
    to_jsonb('WHERE는 FROM 다음, GROUP BY보다 먼저 실행되는 행 단위 필터입니다. 집계 결과 조건은 HAVING에 둡니다.'::text),
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-2-2-cp-01-left-join',
    'sqld',
    2,
    'SQL 기본 및 활용',
    'SQL 활용',
    'SQL 활용',
    'JOIN 4종',
    1,
    1,
    'LEFT OUTER JOIN의 결과로 가장 적절한 설명은?',
    '["양쪽 테이블에서 매칭되는 행만 남긴다","왼쪽 행을 모두 남기고, 매칭 없는 오른쪽 값은 NULL로 채운다","오른쪽 테이블의 행만 모두 남기고 왼쪽은 제거한다","두 테이블의 모든 가능한 조합을 만든다"]'::jsonb,
    1,
    to_jsonb('LEFT OUTER JOIN은 왼쪽 테이블을 기준으로 모두 보존합니다. 오른쪽에 매칭이 없으면 오른쪽 컬럼 값만 NULL이 됩니다.'::text),
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-2-2-cp-04-subquery-place',
    'sqld',
    2,
    'SQL 기본 및 활용',
    'SQL 활용',
    'SQL 활용',
    '서브쿼리',
    1,
    2,
    '서브쿼리의 위치와 이름 연결로 가장 적절한 것은?',
    '["SELECT 절 안의 서브쿼리 — 인라인 뷰","FROM 절 안의 서브쿼리 — 스칼라 서브쿼리","WHERE 절 안의 서브쿼리 — 무조건 DDL","FROM 절 안의 서브쿼리 — 인라인 뷰"]'::jsonb,
    3,
    to_jsonb('FROM 절 안에서 임시 테이블처럼 쓰는 서브쿼리를 인라인 뷰라고 합니다. SELECT 절의 한 행·한 컬럼 서브쿼리는 스칼라 서브쿼리입니다.'::text),
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-2-2-cp-08-rank-dense',
    'sqld',
    2,
    'SQL 기본 및 활용',
    'SQL 활용',
    'SQL 활용',
    '윈도우 함수',
    1,
    2,
    '점수 내림차순이 100, 100, 90일 때 RANK와 DENSE_RANK 결과로 옳은 것은?',
    '["RANK: 1,1,3 / DENSE_RANK: 1,1,2","RANK: 1,2,3 / DENSE_RANK: 1,1,3","RANK: 1,1,2 / DENSE_RANK: 1,1,3","RANK: 1,2,2 / DENSE_RANK: 1,2,3"]'::jsonb,
    0,
    to_jsonb('RANK는 동점 뒤 순위를 건너뛰므로 1,1,3입니다. DENSE_RANK는 동점 뒤에도 순위를 건너뛰지 않아 1,1,2입니다.'::text),
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-2-3-cp-03-savepoint-rollback',
    'sqld',
    2,
    'SQL 기본 및 활용',
    '관리 구문',
    '관리 구문',
    'TCL',
    1,
    2,
    'SAVEPOINT와 ROLLBACK TO에 대한 설명으로 옳은 것은?',
    '["SAVEPOINT는 COMMIT과 같아서 그 지점까지 영구 저장한다","ROLLBACK TO SAVEPOINT는 테이블 구조를 삭제한다","ROLLBACK TO SAVEPOINT는 지정한 저장점 이후의 변경만 되돌릴 수 있다","COMMIT 이후에도 이전 SAVEPOINT로 언제든 돌아갈 수 있다"]'::jsonb,
    2,
    to_jsonb('SAVEPOINT는 트랜잭션 안의 중간 저장점입니다. ROLLBACK TO는 그 저장점 이후 변경을 되돌리지만, COMMIT 이후에는 이전 저장점으로 돌아갈 수 없습니다.'::text),
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-2-3-cp-06-ddl-delete-compare',
    'sqld',
    2,
    'SQL 기본 및 활용',
    '관리 구문',
    '관리 구문',
    'ALTER · DROP · TRUNCATE',
    1,
    2,
    'DELETE, TRUNCATE, DROP 비교로 가장 적절한 것은?',
    '["DELETE는 테이블 구조까지 삭제한다","TRUNCATE는 조건으로 일부 행만 삭제할 때 주로 사용한다","DROP은 행만 비우고 테이블 구조는 유지한다","DELETE는 DML, TRUNCATE와 DROP은 DDL로 분류한다"]'::jsonb,
    3,
    to_jsonb('DELETE는 데이터를 조작하는 DML이고 조건 삭제와 ROLLBACK이 가능합니다. TRUNCATE와 DROP은 DDL로 자동 COMMIT 함정이 있습니다.'::text),
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  ),
  (
    'sqld-2-3-cp-07-pk-unique-null',
    'sqld',
    2,
    'SQL 기본 및 활용',
    '관리 구문',
    '관리 구문',
    '제약조건',
    1,
    2,
    'PK, UNIQUE, NOT NULL의 차이로 가장 적절한 것은?',
    '["PK는 NULL을 허용하고 UNIQUE는 반드시 대표 키가 된다","NOT NULL은 중복을 막는 제약이라 PK와 완전히 같다","UNIQUE는 중복을 막지만 SQLD/Oracle 기준 NULL은 허용될 수 있다","FOREIGN KEY는 같은 테이블 안의 중복 값만 막는 제약이다"]'::jsonb,
    2,
    to_jsonb('PK는 대표 식별자라 UNIQUE + NOT NULL 성격을 가집니다. UNIQUE는 중복을 막지만 대표 키라는 뜻은 아니며, SQLD/Oracle 기준 NULL은 허용될 수 있습니다.'::text),
    'self-reviewed',
    true,
    'src/data/questions/sqld/concept-practice.json',
    now()
  )
on conflict (id) do update
set
  subject = excluded.subject,
  chapter = excluded.chapter,
  chapter_title = excluded.chapter_title,
  topic = excluded.topic,
  canonical_topic = excluded.canonical_topic,
  subtopic = excluded.subtopic,
  pass_number = excluded.pass_number,
  difficulty = excluded.difficulty,
  stem = excluded.stem,
  choices = excluded.choices,
  answer_index = excluded.answer_index,
  explanation = excluded.explanation,
  lifecycle = excluded.lifecycle,
  is_playable = excluded.is_playable,
  source_path = excluded.source_path,
  updated_at = now();
